name = "torchlib"
version = "0.1.0"
defaultTargets = ["TorchLib"]
testDriver = "runTests"
lintDriver = "batteries/runLinter"

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"

[[require]]
name = "lintLlmProofs"
git = "https://github.com/jessealama/lint-llm-proofs"
rev = "main"

[[lean_lib]]
name = "TorchLib"
globs = ["TorchLib.*"]

[[lean_lib]]
name = "TorchLibTests"
globs = ["TorchLibTests.+"]

[[lean_exe]]
name = "runTests"
srcDir = "scripts"
root = "RunTests"

[[lean_exe]]
name = "runExamples"
srcDir = "scripts"
root = "RunExamples"