import TorchLib.Core
import TorchLib.Layers
import TorchLib.Models
import TorchLib.Runtime.Training
import TorchLib.Verification.IBP
import TorchLib.Verification.Certificate

/-!
# Example: Formal Verification on MNIST-scale Inputs

**Problem:** given a small MLP trained on synthetic MNIST-like data (784-dim
inputs, 10 output classes), certify that the predicted class is stable under
ℓ∞ perturbations of radius ε around a test digit.

**Architecture:** configurable via `hiddenDims`.  Default:
`Linear(64 → 32) → ReLU → Linear(32 → 32) → ReLU → Linear(32 → 10)`

We use a miniature 8×8 = 64-dim "image" (rather than the full 28×28 = 784)
so the example runs quickly in the Lean interpreter.  The verification
techniques are identical to what you would apply at full MNIST scale.

**Dataset:** run `python scripts/export_mnist.py` first.  The script
downloads MNIST, average-pools each 28×28 image to 8×8 = 64 dims, and
writes `data/mnist.csv`.  The example loads that CSV at runtime.

**Certification:**
  1. **IBP sweep** — propagates interval bounds through the MLP, checking
     `lo[predicted] > hi[j]` for all rival classes j.
  2. **IBPChecker** — uses the `Certificate` module to issue a formal
     `CertResult` for local ℓ∞-robustness.
-/

open TorchLib TorchLib.Runtime TorchLib.Verification

-- Needed so that `Array.get!` on `MLP.layers` resolves
instance : Inhabited (Linear Float) where
  default := Linear.init 1 1

-- ---------------------------------------------------------------------------
-- Hyper-parameters
-- ---------------------------------------------------------------------------

/-- Input dimensionality (8 × 8 = 64, a miniature "MNIST" image). -/
def inputDim  : Nat := 64
/-- Hidden layer dimensions.  Length = number of hidden layers. -/
def hiddenDims : List Nat := [32, 16]
/-- Number of output classes. -/
def numClasses : Nat := 10
/-- Number of samples per class in the training set. -/
def samplesPerClass : Nat := 4

-- ---------------------------------------------------------------------------
-- CSV loader for real MNIST data
-- ---------------------------------------------------------------------------

/-- Path to the exported MNIST CSV (generated by `scripts/export_mnist.py`). -/
def mnistCsvPath : System.FilePath := "data/mnist.csv"

/-- Parse a decimal float string like "-0.123456" or "42". -/
private def parseFloat? (s : String) : Option Float :=
  let s := s.trimAscii.toString
  if s.isEmpty then none else
  let neg := s.startsWith "-"
  let s := if neg then (s.drop 1).toString else s
  let parts := s.splitOn "."
  match parts with
  | [intPart] =>
    match String.toNat? intPart with
    | some n => let v := Float.ofNat n; some (if neg then -v else v)
    | none   => none
  | [intPart, fracPart] =>
    match String.toNat? intPart, String.toNat? fracPart with
    | some i, some f =>
      let intVal  := Float.ofNat i
      let fracVal := Float.ofScientific f true (String.length fracPart)
      let v := intVal + fracVal
      some (if neg then -v else v)
    | _, _ => none
  | _ => none

/-- Parse one non-comment CSV line: `split,label,v0,v1,...,v31`.
    Returns `(split, label, pixels)` or `none`. -/
private def parseLine (line : String) : Option (String × Nat × Array Float) :=
  let line := line.trimAscii.toString
  if line.startsWith "#" || line.isEmpty then none
  else
    let parts := line.splitOn ","
    match parts with
    | split :: labelStr :: rest =>
      let label := (labelStr.trimAscii.toString).toNat!
      let vals  := rest.toArray.filterMap parseFloat?
      if vals.size == inputDim then some (split.trimAscii.toString, label, vals) else none
    | _ => none

/-- One-hot encode a class label over `numClasses` classes. -/
private def oneHot (label : Nat) : Array Float :=
  Array.replicate numClasses 0.0 |>.set! label 1.0

/-- A simple dataset bundle. -/
structure Dataset where
  trainXs    : Tensor Float
  trainYs    : Tensor Float
  testXs     : Tensor Float
  testYs     : Tensor Float
  trainLabels : Array Nat
  testLabels : Array Nat
  numTrain   : Nat
  numTest    : Nat
  source     : String

/-- Load real MNIST data from CSV.
    Requires `data/mnist.csv` — run `python scripts/export_mnist.py` first. -/
def loadMnistCsv : IO Dataset := do
  let content ← IO.FS.readFile mnistCsvPath
  let lines := content.splitOn "\n"
  let mut trainPixels : Array (Array Float) := #[]
  let mut trainLbls   : Array Nat := #[]
  let mut testPixels  : Array (Array Float) := #[]
  let mut testLbls    : Array Nat := #[]
  for line in lines do
    match parseLine line with
    | some ("train", lbl, vals) =>
      trainPixels := trainPixels.push vals
      trainLbls   := trainLbls.push lbl
    | some ("test", lbl, vals) =>
      testPixels := testPixels.push vals
      testLbls   := testLbls.push lbl
    | _ => pure ()
  if trainPixels.isEmpty then
    throw (IO.userError "No training data found in CSV — run `python scripts/export_mnist.py` first")
  let nTrain := trainPixels.size
  let nTest  := testPixels.size
  let txData := trainPixels.foldl (· ++ ·) #[]
  let tyData := trainLbls.foldl (fun acc l => acc ++ oneHot l) #[]
  let exData := testPixels.foldl (· ++ ·) #[]
  let eyData := testLbls.foldl (fun acc l => acc ++ oneHot l) #[]
  return {
    trainXs    := { shape := [nTrain, inputDim], data := txData }
    trainYs    := { shape := [nTrain, numClasses], data := tyData }
    testXs     := { shape := [nTest, inputDim], data := exData }
    testYs     := { shape := [nTest, numClasses], data := eyData }
    trainLabels := trainLbls
    testLabels := testLbls
    numTrain   := nTrain
    numTest    := nTest
    source     := "real MNIST (data/mnist.csv)"
  }

-- ---------------------------------------------------------------------------
-- Training: MLP with configurable hidden layers, analytic MSE gradients
-- ---------------------------------------------------------------------------
-- The MLP has `hiddenDims.length + 1` layers.  Hidden layers are at indices
-- 0 … hiddenDims.length−1; the output layer is at index hiddenDims.length.
-- We train only the output layer with MSE for simplicity.
-- Hidden-layer weights stay at their init, acting as a fixed random
-- projection — sufficient because the downsampled digits are separable
-- in the projected space.

/-- Deterministic pseudo-random init for the first layer.

    `MLP.init` sets all weights to 0.1 (uniform), which makes every hidden
    neuron compute the same function.  This function replaces layer 0's
    weights with a varied pattern so each hidden unit picks up different
    input features.  -/
private def diverseInitLayer (model : MLP Float) (idx seed : Nat) : MLP Float :=
  let layer := model.layers.get! idx
  match layer.weight.shape with
  | [outF, inF] =>
    let data := Id.run do
      let mut d := layer.weight.data
      for j in [:outF] do
        for i in [:inF] do
          -- Simple hash → varied sign and magnitude (seed offsets per layer)
          let h := (i * 7 + j * 13 + seed + 5) % 17
          let v := (Float.ofNat h / 8.5 - 1.0) * 0.2
          d := d.set! (j * inF + i) v
      return d
    let newLayer : Linear Float := { layer with weight := { layer.weight with data } }
    { model with layers := model.layers.set! idx newLayer }
  | _ => model

private def diverseInit (model : MLP Float) : MLP Float :=
  let numHidden := hiddenDims.length
  Id.run do
    let mut m := model
    for idx in [:numHidden] do
      m := diverseInitLayer m idx (idx * 37)
    return m

/-- One SGD step updating only the output layer (last layer). -/
def trainStep (cfg : SGDConfig) (st : SGDState)
    (model : MLP Float) (xs ys : Tensor Float)
    : SGDState × MLP Float × Float :=
  let batch  := (xs.shape.headD 1).toFloat
  let batchN := xs.shape.headD 1
  let outIdx := hiddenDims.length   -- index of the output layer
  -- Forward pass
  let pred := MLP.forward model xs
  let loss := mseLoss pred ys
  -- Compute hidden activations through all hidden layers (each: linear + relu)
  let hidden := Id.run do
    let mut h := xs
    for idx in [:outIdx] do
      h := Linear.forward (model.layers.get! idx) h |>.apply Scalar.relu
    return h
  -- Gradients for the output layer: pred = hidden @ W_out^T + b_out
  let diff := pred - ys
  let lOut := model.layers.get! outIdx
  let gradW := Tensor.matmul diff.transpose hidden
                 |>.map (· * (2.0 / batch))
  let ones : Tensor Float := Tensor.ones [batchN, 1]
  let gradB := Tensor.matmul diff.transpose ones
                 |>.flatten |>.map (· * (2.0 / batch))
  -- SGD update
  let r  := SGD.step cfg st [("wOut", lOut.weight, gradW), ("bOut", lOut.bias, gradB)]
  let st' := r.1
  let ps  := r.2
  let w'  := ps.find? (fun p => p.1 == "wOut") |>.map (·.2) |>.getD lOut.weight
  let b'  := ps.find? (fun p => p.1 == "bOut") |>.map (·.2) |>.getD lOut.bias
  let newLOut : Linear Float := { weight := w', bias := b' }
  let layers' := model.layers.set! outIdx newLOut
  (st', { model with layers := layers' }, loss)

/-- Train the MLP for `n` steps and return the trained model. -/
def trainMLP (xs ys : Tensor Float) (n : Nat) (lr : Float := 0.01)
    : IO (MLP Float) := do
  let cfg : SGDConfig := { lr }
  let mut model := diverseInit (MLP.init inputDim hiddenDims numClasses)
  let mut st    := SGD.initState cfg ["wOut", "bOut"]
  for i in [:n] do
    let (st', model', loss) := trainStep cfg st model xs ys
    st    := st'
    model := model'
    if i % 10 == 0 then
      IO.println s!"  step {i}: MSE = {loss}"
  return model

-- ---------------------------------------------------------------------------
-- Helper: argmax
-- ---------------------------------------------------------------------------

private def argmax (data : Array Float) : Nat :=
  Id.run do
    let mut bestIdx := 0
    let mut bestVal := data.getD 0 (-1.0e30)
    for i in [:data.size] do
      if data.get! i > bestVal then
        bestIdx := i
        bestVal := data.get! i
    return bestIdx

-- ---------------------------------------------------------------------------
-- Accuracy
-- ---------------------------------------------------------------------------

/-- Compute classification accuracy: run the model on each sample, compare
    `argmax(logits)` against the true label.  Returns (correct, total). -/
private def computeAccuracy (model : MLP Float) (xs : Tensor Float)
    (labels : Array Nat) : Nat × Nat :=
  let n := labels.size
  Id.run do
    let mut correct := 0
    for i in [:n] do
      let row : Tensor Float :=
        { shape := [1, inputDim]
          data  := xs.data.extract (i * inputDim) ((i + 1) * inputDim) }
      let logits := MLP.forward model row
      let pred := argmax logits.data
      if pred == labels.getD i 0 then
        correct := correct + 1
    return (correct, n)

-- ---------------------------------------------------------------------------
-- IBP certification for multi-class MLP
-- ---------------------------------------------------------------------------

/-- Run IBP through the MLP and return `(lo, hi)` output bound tensors. -/
def ibpCertify (model : MLP Float) (x : Tensor Float) (eps : Float)
    : Tensor Float × Tensor Float :=
  IBP.mlpBounds model x eps

/-- Check whether class `c` dominates all rivals under IBP bounds. -/
def ibpIsCertified (lo hi : Tensor Float) (c : Nat) : Bool :=
  let n := lo.numel
  let cLo := lo.data.getD c 0.0
  (List.range n).all (fun j => j == c || hi.data.getD j 0.0 < cLo)

-- ---------------------------------------------------------------------------
-- Main
-- ---------------------------------------------------------------------------

def main : IO Unit := do
  IO.println "╔════════════════════════════════╗"
  IO.println "║  Formal Verification on MNIST  ║"
  IO.println "╚════════════════════════════════╝"

  -- 0. Load dataset
  let ds ← loadMnistCsv
  IO.println s!"\nDataset: {ds.source}"
  IO.println s!"  train samples: {ds.numTrain}  |  test samples: {ds.numTest}"

  -- 1. Train the network
  let archStr := String.intercalate " → " <|
    [toString inputDim] ++ hiddenDims.map toString ++ [toString numClasses]
  IO.println ""
  IO.println s!"=== Training MLP({archStr}) ==="
  let model ← trainMLP ds.trainXs ds.trainYs 200 (lr := 0.1)

  -- 1b. Train & test accuracy
  IO.println ""
  IO.println "=== Accuracy ==="
  let (trainCorrect, trainTotal) := computeAccuracy model ds.trainXs ds.trainLabels
  let trainAcc := Float.ofNat trainCorrect / Float.ofNat (max trainTotal 1) * 100.0
  IO.println s!"  train: {trainCorrect}/{trainTotal} ({trainAcc}%)"
  let (testCorrect, testTotal) := computeAccuracy model ds.testXs ds.testLabels
  let testAcc := Float.ofNat testCorrect / Float.ofNat (max testTotal 1) * 100.0
  IO.println s!"  test:  {testCorrect}/{testTotal} ({testAcc}%)"

  -- 2. Nominal forward pass on the first test digit
  IO.println ""
  IO.println "=== Nominal forward pass (first test digit) ==="
  let x0 : Tensor Float :=
    { shape := [1, inputDim]
      data  := ds.testXs.data.extract 0 inputDim }
  let trueLabel := ds.testLabels.getD 0 0
  let nomOut := MLP.forward model x0
  let predClass := argmax nomOut.data
  IO.println s!"true label:       {trueLabel}"
  IO.println s!"logits (first 5): {reprStr (nomOut.data.extract 0 5)}"
  IO.println s!"predicted class:  {predClass}"

  -- 3. IBP certification sweep
  IO.println ""
  IO.println "=== IBP certification sweep ==="
  IO.println "  Checking: ∀ x′ ∈ B_ε(x₀), argmax f(x′) = predicted class"
  IO.println ""
  for eps in ([0.001, 0.005, 0.01, 0.02, 0.05, 0.1] : List Float) do
    let (lo, hi) := ibpCertify model x0 eps
    let certified := ibpIsCertified lo hi predClass
    let classLo := lo.data.getD predClass 0.0
    -- Find the tightest rival upper bound
    let rivalHi := Id.run do
      let mut best := -1.0e30
      for j in [:numClasses] do
        if j != predClass then
          let v := hi.data.getD j 0.0
          if v > best then best := v
      return best
    let margin := classLo - rivalHi
    let status := if certified then "CERTIFIED ✓" else "not certified"
    IO.println s!"  ε = {eps}:  margin = {margin}  → {status}"

  -- 4. Certificate module (IBPChecker)
  IO.println ""
  IO.println "=== IBPChecker (Certificate module) ==="
  let checker : IBPChecker := { model }
  let query := CertQuery.localRobustness x0 0.005 predClass
  let result := Checker.check checker query
  match result with
  | .certified lo hi =>
    IO.println s!"  Result: CERTIFIED"
    IO.println s!"  lo bounds (first 5): {reprStr (lo.data.extract 0 5)}"
    IO.println s!"  hi bounds (first 5): {reprStr (hi.data.extract 0 5)}"
  | .violated ce =>
    IO.println s!"  Result: VIOLATED (counter-example dims = {ce.numel})"
  | .unknown reason =>
    IO.println s!"  Result: UNKNOWN — {reason}"

  -- 5. Issue and serialise a certificate
  IO.println ""
  IO.println "=== Certificate serialisation ==="
  let (lo5, hi5) := ibpCertify model x0 0.005
  let cert : Certificate :=
    { query    := s!"localRobustness(center=x0, eps=0.005, class={predClass})"
      method   := "IBP"
      boundsLo := lo5
      boundsHi := hi5
      valid    := ibpIsCertified lo5 hi5 predClass
      metadata := [("tool", "lean4torch"), ("dataset", "MNIST")] }
  IO.println (cert.serialise)

  -- 6. Independent re-verification
  IO.println "=== Re-verification ==="
  let (freshLo, freshHi) := ibpCertify model x0 0.005
  let ok := cert.verify freshLo freshHi
  IO.println s!"  Fresh bounds match certificate: {ok}"

#eval! main
